package services

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/openagenthub/backend/internal/database"
	"github.com/openagenthub/backend/internal/models"
)

// syncbundle aggregates workspace/project/user configuration and renders local snapshot files,
// for the hub.sync_project tool and openagent CLI to write into the project's .openagent/ directory.
//
// Design highlights:
//   - One-way sync (server -> local); files are read-only snapshots; the source of truth is in the Console.
//   - Shared data (rules, project info, skills) and personal data (profile, memories) are physically separated:
//     all personal data goes into the local/ subdirectory, excluded from commits by a generated .gitignore.
//   - Content must be rendered deterministically (no timestamps) so the ETag remains stable.

const (
	ManagedBlockBegin = "<!-- openagenthub:begin -->"
	ManagedBlockEnd   = "<!-- openagenthub:end -->"

	// ConfigDir is the snapshot directory name inside the project.
	ConfigDir = ".openagent"

	generatedHeader = "<!-- Generated by Open Agent Hub. Do not edit; manage in the console and refresh via `openagent sync` or hub.sync_project. -->"
)

// SyncFile represents a single file in the sync snapshot (Path is relative to the project root).
type SyncFile struct {
	Path    string `json:"path"`
	Content string `json:"content"`
	Hash    string `json:"hash"`
}

// SyncBundle is the complete result of one sync.
type SyncBundle struct {
	ETag         string          `json:"etag"`
	Project      *models.Project `json:"project,omitempty"`
	Files        []SyncFile      `json:"files"`
	ManagedBlock string          `json:"managed_block"`
	ManagedFiles []string        `json:"managed_files"`
}

// NormalizeRepoPath normalizes a project path: removes redundant separators and trailing slashes,
// so different spellings of the same directory (with/without trailing slash) match the same project.
func NormalizeRepoPath(p string) string {
	p = strings.TrimSpace(p)
	if p == "" {
		return ""
	}
	p = filepath.Clean(p)
	if p != "/" {
		p = strings.TrimRight(p, "/")
	}
	return p
}

// RepoNameFromPath extracts the leaf directory name from the path, used as a cross-machine fallback match key.
func RepoNameFromPath(p string) string {
	p = NormalizeRepoPath(p)
	if p == "" || p == "/" {
		return ""
	}
	return filepath.Base(p)
}

// NormalizeGitRemote normalizes a git remote URL so different spellings of the same repo match:
//
//	git@github.com:org/repo.git               -> github.com/org/repo
//	https://github.com/org/repo.git           -> github.com/org/repo
//	https://user:token@github.com/org/repo    -> github.com/org/repo
//	ssh://git@github.com:22/org/repo.git      -> github.com/org/repo
//
// Rules: strip protocol/credentials, lowercase host, strip .git suffix, strip leading/trailing slashes.
// Returns the whitespace-trimmed lowercase original when parsing fails.
func NormalizeGitRemote(raw string) string {
	s := strings.TrimSpace(raw)
	if s == "" {
		return ""
	}
	// Strip protocol prefix (scheme://).
	if i := strings.Index(s, "://"); i >= 0 {
		s = s[i+3:]
	}
	// scp-style git@host:org/repo - treat the first ':' as the host/path separator.
	// Strip userinfo (everything before '@').
	if at := strings.Index(s, "@"); at >= 0 {
		s = s[at+1:]
	}
	// Separator between host and path: prefer '/', otherwise scp's ':'.
	if slash := strings.IndexAny(s, "/:"); slash >= 0 {
		host := strings.ToLower(s[:slash])
		path := strings.TrimLeft(s[slash+1:], "/:")
		// Strip scp port like host:22/... (only handle host port; do not touch path starting with digits+'/')
		if p := strings.Index(host, ":"); p >= 0 {
			host = host[:p]
		}
		s = host + "/" + path
	} else {
		s = strings.ToLower(s)
	}
	s = strings.Trim(s, "/")
	s = strings.TrimSuffix(s, ".git")
	s = strings.Trim(s, "/")
	return s
}

// FindProjectByIdentity resolves a project within a workspace by cross-machine priority:
// git_remote normalized exact match > repo_path exact match (same machine) > repo_name unique hit (fallback).
// Returns on first match; if repo_name has more than one hit, it is ambiguous and nil is returned (to avoid mis-binding).
func FindProjectByIdentity(workspaceID, repoPath, gitRemote string) *models.Project {
	if remote := NormalizeGitRemote(gitRemote); remote != "" {
		var p models.Project
		if err := database.DB.Where("workspace_id = ? AND git_remote = ? AND status = ?",
			workspaceID, remote, "active").First(&p).Error; err == nil {
			return &p
		}
	}
	if p := FindProjectByPath(workspaceID, repoPath); p != nil {
		return p
	}
	if name := RepoNameFromPath(repoPath); name != "" {
		var matches []models.Project
		if err := database.DB.Where("workspace_id = ? AND repo_name = ? AND status = ?",
			workspaceID, name, "active").Limit(2).Find(&matches).Error; err == nil && len(matches) == 1 {
			return &matches[0]
		}
	}
	return nil
}

// FindProjectByPath exact-matches a project in the workspace by normalized repo_path (same machine).
func FindProjectByPath(workspaceID, repoPath string) *models.Project {
	repoPath = NormalizeRepoPath(repoPath)
	if repoPath == "" {
		return nil
	}
	var p models.Project
	err := database.DB.Where("workspace_id = ? AND repo_path = ? AND status = ?",
		workspaceID, repoPath, "active").First(&p).Error
	if err != nil {
		return nil
	}
	return &p
}

// BuildSyncBundle aggregates and renders snapshot files. project may be nil (workspace-level content only).
func BuildSyncBundle(workspaceID, userID string, project *models.Project) (*SyncBundle, error) {
	var projectID *string
	if project != nil {
		projectID = &project.ID
	}

	files := []SyncFile{
		newSyncFile(ConfigDir+"/rules.md", renderRulesFile(workspaceID, projectID)),
		newSyncFile(ConfigDir+"/local/profile.md", renderProfileFile(userID)),
		newSyncFile(ConfigDir+"/local/memories.md", renderMemoriesFile(workspaceID, projectID)),
		newSyncFile(ConfigDir+"/.gitignore", "# Personal data and machine state must never be committed.\nlocal/\n"),
	}
	if project != nil {
		files = append(files, newSyncFile(ConfigDir+"/project.md", renderProjectFile(project)))
	}
	files = append(files, renderSkillFiles(workspaceID, projectID)...)
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })

	h := sha256.New()
	for _, f := range files {
		h.Write([]byte(f.Path + ":" + f.Hash + ";"))
	}

	return &SyncBundle{
		ETag:         hex.EncodeToString(h.Sum(nil))[:32],
		Project:      project,
		Files:        files,
		ManagedBlock: RenderManagedBlock(project),
		ManagedFiles: []string{"CLAUDE.md", "AGENTS.md"},
	}, nil
}

func newSyncFile(path, content string) SyncFile {
	h := sha256.Sum256([]byte(content))
	return SyncFile{Path: path, Content: content, Hash: hex.EncodeToString(h[:])[:32]}
}

// RenderManagedBlock renders the managed block for CLAUDE.md / AGENTS.md (including markers).
func RenderManagedBlock(project *models.Project) string {
	var b strings.Builder
	b.WriteString(ManagedBlockBegin + "\n")
	b.WriteString("## Open Agent Hub\n\n")
	b.WriteString("This project is connected to Open Agent Hub (MCP server `hub`).\n\n")
	b.WriteString("- At session start, check freshness first: if MCP is available, call `hub.sync_project` with this repository's absolute `project_path` and the local `.openagent/local/state.json` ETag when available. If the tool reports changes, refresh the returned files or ask the user to run `openagent sync`.\n")
	b.WriteString("- After the freshness check, read `.openagent/rules.md` (team rules); also read `.openagent/local/profile.md` and `.openagent/local/memories.md` if present (personal profile, preferences, and key memories).\n")
	if project != nil {
		b.WriteString("- Project context lives in `.openagent/project.md`.\n")
	}
	b.WriteString("- Team skills live under `.openagent/skills/` (one directory per skill, see `skills/index.json`).\n")
	b.WriteString("- Search team memory with `hub.search_memory`; persist new knowledge via `hub.propose_memory` (never edit the snapshot files directly).\n")
	b.WriteString("- Before invoking external tools, check `hub.get_tool_policy`.\n")
	b.WriteString(ManagedBlockEnd)
	return b.String()
}

// RenderSyncInstructions renders the local write instruction text for AI Agents.
// The MCP server can only return data, not write files to the client; these instructions
// tell the Agent exactly how to persist the files returned by sync_project into .openagent/,
// inject the managed_block into CLAUDE.md/AGENTS.md using markers, and persist the etag
// for the next incremental sync. Only included in the response when changed=true.
func RenderSyncInstructions(bundle *SyncBundle) string {
	var b strings.Builder
	b.WriteString("Persist this sync to disk now — MCP cannot write files for you, so use your own file-writing tools. All paths are relative to the project root (your current working directory).\n\n")

	// Step 1: write snapshot files
	b.WriteString("1) Write the snapshot files: for each object in the \"files\" array, create any missing parent directories and write its \"content\" to its \"path\", overwriting any existing file (these are managed snapshots, not user-edited files). Files include .openagent/rules.md, .openagent/local/profile.md, .openagent/local/memories.md, .openagent/.gitignore")
	if bundle.Project != nil {
		b.WriteString(", .openagent/project.md")
	}
	b.WriteString(", and .openagent/skills/**/SKILL.md plus .openagent/skills/index.json.\n\n")

	// Step 2: inject managed block
	b.WriteString("2) Inject the managed block: for each filename in \"managed_files\" (typically CLAUDE.md and AGENTS.md) at the project root, update it with the \"managed_block\" string using these rules:\n")
	b.WriteString("   - If the file already contains both markers \"" + ManagedBlockBegin + "\" and \"" + ManagedBlockEnd + "\" (begin before end): replace everything from the begin marker through the end marker, inclusive, with the full \"managed_block\" string. Keep all content before the begin marker and after the end marker unchanged.\n")
	b.WriteString("   - Else if the file is missing or empty/whitespace-only: create/overwrite it with \"managed_block\" followed by a single newline.\n")
	b.WriteString("   - Else (file has content but no markers): append two newlines, then the full \"managed_block\" string, then a single newline. Do not modify existing content.\n")
	b.WriteString("   The \"managed_block\" string already contains the begin/end markers — do not add extra markers.\n\n")

	// Step 3: persist etag (recommended)
	b.WriteString("3) (Recommended) Persist the etag: write .openagent/local/state.json with {\"etag\":\"" + bundle.ETag + "\"} so the next hub.sync_project can skip unchanged content. If you skip this, reuse the etag from this response on the next sync.\n\n")

	// Step 4: read context
	b.WriteString("4) After writing, read .openagent/rules.md")
	if bundle.Project != nil {
		b.WriteString(" and .openagent/project.md")
	}
	b.WriteString(", plus .openagent/local/profile.md and .openagent/local/memories.md, to load your context.")

	// Step 5: gitignore
	b.WriteString("\n\n5) If this is a git repository (a .git/ directory exists at the project root), ensure .openagent/ is listed in .gitignore to prevent committing local snapshots: if .gitignore exists, check each line for \".openagent\" and append it if missing; if .gitignore does not exist, create it with \".openagent/\" as the only entry.")

	return b.String()
}

// UpsertManagedBlock idempotently writes the managed block into a document:
// if markers already exist, replaces the block content; otherwise appends to the end.
// User content outside the block is never touched.
func UpsertManagedBlock(doc, block string) string {
	begin := strings.Index(doc, ManagedBlockBegin)
	end := strings.Index(doc, ManagedBlockEnd)
	if begin >= 0 && end > begin {
		return doc[:begin] + block + doc[end+len(ManagedBlockEnd):]
	}
	if strings.TrimSpace(doc) == "" {
		return block + "\n"
	}
	return strings.TrimRight(doc, "\n") + "\n\n" + block + "\n"
}

func renderRulesFile(workspaceID string, projectID *string) string {
	rules := ResolveEffectiveRules(workspaceID, projectID, nil)

	var b strings.Builder
	b.WriteString(generatedHeader + "\n\n")
	b.WriteString("# Team Rules\n\n")
	if len(rules) == 0 {
		b.WriteString("(No rules defined yet. Manage rules in the Open Agent Hub console.)\n")
		return b.String()
	}

	// Group by Type, maintaining the resolver's deterministic order within each group
	groups := map[string][]EffectiveRule{}
	var types []string
	for _, r := range rules {
		if _, ok := groups[r.Type]; !ok {
			types = append(types, r.Type)
		}
		groups[r.Type] = append(groups[r.Type], r)
	}
	sort.Strings(types)

	for _, t := range types {
		b.WriteString(fmt.Sprintf("## %s\n\n", t))
		for _, r := range groups[t] {
			b.WriteString(fmt.Sprintf("### %s\n\n", r.Name))
			if r.Description != "" {
				b.WriteString(r.Description + "\n\n")
			}
			b.WriteString(r.Value + "\n\n")
			b.WriteString(fmt.Sprintf("> scope: %s · version: %d\n\n", r.OriginScope, r.Version))
		}
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func renderProjectFile(p *models.Project) string {
	var b strings.Builder
	b.WriteString(generatedHeader + "\n\n")
	b.WriteString("# Project: " + p.Name + "\n\n")
	if p.Description != "" {
		b.WriteString(p.Description + "\n\n")
	}
	b.WriteString(fmt.Sprintf("- slug: `%s`\n- project_id: `%s`\n", p.Slug, p.ID))
	if p.Stack != "" && p.Stack != "[]" && p.Stack != "{}" {
		b.WriteString("\n## Tech Stack\n\n```json\n" + p.Stack + "\n```\n")
	}
	if p.Structure != "" && p.Structure != "[]" && p.Structure != "{}" {
		b.WriteString("\n## Structure\n\n```json\n" + p.Structure + "\n```\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func renderProfileFile(userID string) string {
	var user models.User
	database.DB.First(&user, "id = ?", userID)

	var b strings.Builder
	b.WriteString(generatedHeader + "\n\n")
	b.WriteString("# User Profile\n\n")
	if user.DisplayName != "" {
		b.WriteString("- name: " + user.DisplayName + "\n")
	}
	if user.Username != "" {
		b.WriteString("- username: " + user.Username + "\n")
	}
	if profile, err := RenderPersonalProfile(userID); err == nil {
		b.WriteString("\n" + profile)
	} else {
		b.WriteString("\n## Output Preferences\n\n")
		b.WriteString("(Failed to load preferences.)\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// renderSkillFiles renders type=skill memories as skills/<slug>/SKILL.md files,
// plus a skills/index.json manifest (used by the CLI for deletion detection and display).
// When there are no skills, an empty manifest is still emitted so the skills/ directory
// semantics remain stable.
func renderSkillFiles(workspaceID string, projectID *string) []SyncFile {
	type skillFileEntry struct {
		Source      string
		Dir         string
		Name        string
		Description string
		Content     string
		MemoryID    string
		TemplateID  string
		InstallID   string
		Version     int
		Pinned      bool
	}

	entries := []skillFileEntry{}

	q := database.DB.Where("workspace_id = ? AND type = 'skill' AND state = ?", workspaceID, "active")
	if projectID != nil {
		q = q.Where("project_id IS NULL OR project_id = ?", *projectID)
	} else {
		q = q.Where("project_id IS NULL")
	}
	var skills []models.Memory
	q.Order("created_at asc, id asc").Find(&skills)

	for _, s := range skills {
		name, description := skillNameAndDescription(s.Content)
		entries = append(entries, skillFileEntry{
			Source:      "custom",
			Dir:         "custom/" + slugifySkillName(name) + "-" + s.ID[:8],
			Name:        name,
			Description: description,
			Content:     s.Content,
			MemoryID:    s.ID,
			Version:     s.Version,
			Pinned:      s.Pinned,
		})
	}

	installQ := database.DB.Where("workspace_id = ? AND state = ?", workspaceID, "active")
	if projectID != nil {
		installQ = installQ.Where("project_id IS NULL OR project_id = ?", *projectID)
	} else {
		installQ = installQ.Where("project_id IS NULL")
	}
	var installs []models.SkillInstall
	installQ.Order("pinned DESC, created_at ASC, id ASC").Find(&installs)
	for _, install := range installs {
		var tpl models.PublicSkillTemplate
		if err := database.DB.Where("id = ? AND status = ?", install.TemplateID, "active").First(&tpl).Error; err != nil {
			continue
		}
		content := install.OverrideContent
		if content == "" {
			content = tpl.Content
		}
		entries = append(entries, skillFileEntry{
			Source:      "public",
			Dir:         "public/" + slugifySkillName(tpl.Slug) + "-v" + fmt.Sprint(install.InstalledVersion) + "-" + install.ID[:8],
			Name:        tpl.Name,
			Description: tpl.Description,
			Content:     content,
			TemplateID:  tpl.ID,
			InstallID:   install.ID,
			Version:     install.InstalledVersion,
			Pinned:      install.Pinned,
		})
	}

	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Source != entries[j].Source {
			return entries[i].Source < entries[j].Source
		}
		if entries[i].Pinned != entries[j].Pinned {
			return entries[i].Pinned
		}
		if entries[i].Name != entries[j].Name {
			return entries[i].Name < entries[j].Name
		}
		return entries[i].Dir < entries[j].Dir
	})

	type indexEntry struct {
		Dir        string `json:"dir"`
		Name       string `json:"name"`
		Source     string `json:"source"`
		MemoryID   string `json:"memory_id,omitempty"`
		TemplateID string `json:"template_id,omitempty"`
		InstallID  string `json:"install_id,omitempty"`
		Version    int    `json:"version"`
	}

	files := make([]SyncFile, 0, len(entries)+1)
	index := make([]indexEntry, 0, len(entries))
	for _, e := range entries {
		// The name in frontmatter must be a valid skill identifier (lowercase alphanumeric + hyphens, ≤64),
		// use the directory basename (already in slug-id form), same as the directory name —— follows the Anthropic skill convention.
		// Cannot use e.Name directly (it may be a mixed-case/spaced/truncated "..." natural language title).
		skillName := e.Dir[strings.LastIndex(e.Dir, "/")+1:]
		files = append(files, newSyncFile(
			ConfigDir+"/skills/"+e.Dir+"/SKILL.md",
			renderSkillMarkdown(skillName, e.Description, e.Content),
		))
		index = append(index, indexEntry{
			Dir:        e.Dir,
			Name:       e.Name,
			Source:     e.Source,
			MemoryID:   e.MemoryID,
			TemplateID: e.TemplateID,
			InstallID:  e.InstallID,
			Version:    e.Version,
		})
	}

	idx, _ := json.MarshalIndent(index, "", "  ")
	files = append(files, newSyncFile(ConfigDir+"/skills/index.json", string(idx)+"\n"))
	return files
}

// renderSkillMarkdown renders a single SKILL.md. skillName must be a valid skill identifier
// (lowercase alphanumeric + hyphens, passed by the caller using the directory basename); description is a human-readable summary.
func renderSkillMarkdown(skillName, description, content string) string {
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("name: " + yamlQuote(skillName) + "\n")
	b.WriteString("description: " + yamlQuote(description) + "\n")
	b.WriteString("---\n\n")
	b.WriteString(generatedHeader + "\n\n")
	b.WriteString(strings.TrimRight(content, "\n") + "\n")
	return b.String()
}

// yamlQuote wraps a YAML value in double quotes, escaping internal double quotes and backslashes,
// ensuring that values with special characters (e.g. colon+space) do not break frontmatter parsing.
func yamlQuote(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	return "\"" + s + "\""
}

// skillNameAndDescription derives the name (first heading or first line) and description (first non-heading paragraph) from the skill content.
func skillNameAndDescription(content string) (string, string) {
	name, description := "", ""
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "#") {
			if name == "" {
				name = strings.TrimSpace(strings.TrimLeft(line, "# "))
			}
			continue
		}
		if name == "" {
			name = line
		} else if description == "" {
			description = line
		}
		if name != "" && description != "" {
			break
		}
	}
	if name == "" {
		name = "Untitled Skill"
	}
	if description == "" {
		description = name
	}
	if r := []rune(name); len(r) > 80 {
		name = string(r[:77]) + "..."
	}
	if r := []rune(description); len(r) > 200 {
		description = string(r[:197]) + "..."
	}
	return name, description
}

func slugifySkillName(name string) string {
	var b strings.Builder
	lastDash := true
	for _, r := range strings.ToLower(name) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			lastDash = false
		default:
			if !lastDash {
				b.WriteByte('-')
				lastDash = true
			}
		}
	}
	s := strings.Trim(b.String(), "-")
	if s == "" {
		return "skill"
	}
	if len(s) > 48 {
		s = strings.Trim(s[:48], "-")
	}
	return s
}

func renderMemoriesFile(workspaceID string, projectID *string) string {
	q := database.DB.Where("workspace_id = ? AND state = ?", workspaceID, "active").
		Where("pinned = ? OR importance >= ?", true, 0.8)
	if projectID != nil {
		q = q.Where("project_id IS NULL OR project_id = ?", *projectID)
	} else {
		q = q.Where("project_id IS NULL")
	}
	var memories []models.Memory
	q.Order("importance desc, created_at asc").Limit(50).Find(&memories)

	var b strings.Builder
	b.WriteString(generatedHeader + "\n\n")
	b.WriteString("# Key Memories\n\n")
	if len(memories) == 0 {
		b.WriteString("(No pinned or high-importance memories yet.)\n")
		return b.String()
	}
	for _, m := range memories {
		var tags []string
		_ = json.Unmarshal([]byte(m.Tags), &tags)
		b.WriteString("- " + m.Content)
		meta := []string{m.Type}
		if len(tags) > 0 {
			meta = append(meta, strings.Join(tags, ", "))
		}
		if m.Pinned {
			meta = append(meta, "pinned")
		}
		b.WriteString(" _(" + strings.Join(meta, " · ") + ")_\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}
